apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c38y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-c38y@sha256:bfcbf8c439c77805f1a20a3c3fc59deb64a399a5168bc4a4fb21ad053953515f
        name: my-nodejs
        resources: {}
status: {}
